baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'LaxMenner'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "Socials"
imageUrl = "home/home.png"
imageTitle = "<me irl>"
imageWidth = 250
imageHeight = 250

[[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

[[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/LaxMenner"


[[params.socialIcons]]
name = "mastodon"
url = "https://chaos.social/@LaxMenner"

[[params.socialIcons]]
name = "github"
url = "https://github.com/LaxMenner"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/maximilian-lenner-294139223/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/"

[[params.socialIcons]]
name = "buymeacoffee"
url = "https://www.buymeacoffee.com/"